services:
  backend:
    build:
      context: ./backend
    command: npm run dev
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: mysql

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "5173:4173"  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    healthcheck:
      test: wget --spider -q http://localhost:5173 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: ./tests
    volumes:
      - ./tests:/e2e
      - /app/node_modules
    working_dir: /e2e
    networks:
      - app-network
    environment:
      - CYPRESS_BASE_URL=http://frontend:5173
    depends_on:
      - frontend


networks:
  app-network:
    driver: bridge
